# Generated by Django 3.2.6 on 2023-12-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('birthday', models.DateField()),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Мужчина'), (2, 'Женщина')], default=2, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_post', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_job', models.DateField()),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'db_table': 'teachers',
            },
        ),
    ]
