# Generated by Django 3.2.6 on 2023-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_group', models.IntegerField(blank=True, default=1, null=True)),
                ('number_1_students', models.IntegerField(blank=True, default=1, null=True)),
                ('date_1_creation', models.DateField(blank=True, null=True)),
                ('date_2_creation', models.DateField(blank=True, null=True)),
                ('data_teacher', models.PositiveSmallIntegerField(blank=True, choices=[])),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'groups',
            },
        ),
    ]
