# Generated by Django 3.2.6 on 2023-12-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_students_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='data_teacher',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', '123123 123 123')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Мужчина'), (2, 'Женщина')], null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='date_job',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужчина'), ('FEMALE', 'Женщина')], max_length=10, null=True),
        ),
    ]
