# Generated by Django 3.2.6 on 2023-12-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20231217_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='data_teacher',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '123123123 123 123')]),
        ),
    ]
