# Generated by Django 3.2.6 on 2023-12-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20231217_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='data_teacher',
            field=models.CharField(blank=True, choices=[('1', '123123123 123 123'), ('2', '123 123 123')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='number_group',
            field=models.CharField(blank=True, choices=[('1', 123)], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='number_group',
            field=models.CharField(blank=True, choices=[('1', 123)], max_length=100, null=True),
        ),
    ]
