# Generated by Django 3.2.6 on 2023-12-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20231217_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
