# Generated by Django 3.2.6 on 2023-12-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('MALE', 'Мужчина'), ('FEMALE', 'Женщина')], max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_join', models.DateField(blank=True, null=True)),
                ('date_leave', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number_group', models.CharField(blank=True, choices=[], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_work', models.IntegerField(blank=True, default=1, null=True)),
                ('date_1', models.DateField(blank=True, null=True)),
                ('number_1_students', models.IntegerField(blank=True, default=1, null=True)),
                ('number_2_students', models.IntegerField(blank=True, default=1, null=True)),
                ('description_work', models.CharField(blank=True, max_length=1000, null=True)),
                ('number_group', models.CharField(blank=True, choices=[], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'db_table': 'works',
            },
        ),
    ]
